### index req
GET http://localhost:6688/

### message list req
GET http://localhost:6688/api/chat/123/messages

### chat req
GET http://localhost:6688/api/chat


### notify-server index
GET http://localhost:6687/
